#-*- coding:utf-8 -*-

"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?"""

import common

def multiply(ls):
	res = 1
	for i in ls:
		res *=i
	return res

primes = common.getPrimes(10**5)


triangles =[n*(n+1)/2 for n in range(0,10**5)]

result = -1

for i in triangles:
	pDivs = common.getPrimeDivisors(i,primes)
	numDivs = 1
	for j in common.unifyList(pDivs):
		numDivs *= (1+ pDivs.count(j))
	if numDivs>=500:
		result = i
		break

print "result : "+ str(result)
