#-*- coding: utf-8 -*-

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


fibs = [1,2]
while fibs[len(fibs)-1] < 4*10**6:
	fibs.append(fibs[len(fibs)-2]+fibs[len(fibs)-1])

evenfibs = [x for x in fibs if x % 2 == 0]

print "result : " + str(sum(evenfibs))
